pre_process...
Traceback (most recent call last):
  File "exec.py", line 2, in <module>
    exec(open("pre_process.py").read())
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pandas'
<string>:22: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
<string>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<string>:22: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
<string>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<string>:22: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
<string>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<string>:22: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
<string>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<string>:22: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
<string>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<string>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<string>:22: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
<string>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<string>:22: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
<string>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/munak98/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 4 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 4 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 4 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 4 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 4 are removed. Consider decreasing the number of bins.
  warnings.warn(
/home/munak98/.local/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  warnings.warn(
pre_process...
6000000
[0, 6000000]
2451520
[6000000, 8451520]
6000000
[8451520, 14451520]
4310733
[14451520, 18762253]
6000000
[18762253, 24762253]
349783
[24762253, 25112036]
6000000
[25112036, 31112036]
175897
[31112036, 31287933]
5-folds...
1
2
3
4
5
undersampling...
1
2
3
4
5
process...
[array(['ICMP ', 'TCP  ', 'UDP  '], dtype=object), array(['......', '....S.', '...R..', '...RS.', '.A....', '.A...F',
       '.A..S.', '.A..SF', '.A.R..', '.A.R.F', '.A.RS.', '.A.RSF',
       '.AP...', '.AP..F', '.AP.S.', '.AP.SF', '.APR..', '.APR.F',
       '.APRS.', '.APRSF'], dtype=object), array(['bruteForce', 'dos', 'normal', 'pingScan', 'portScan'],
      dtype=object)]
[array(['ICMP ', 'TCP  ', 'UDP  '], dtype=object), array(['......', '....S.', '...R..', '...RS.', '.A....', '.A...F',
       '.A..S.', '.A..SF', '.A.R..', '.A.R.F', '.A.RS.', '.A.RSF',
       '.AP...', '.AP..F', '.AP.S.', '.AP.SF', '.APR..', '.APR.F',
       '.APRS.', '.APRSF'], dtype=object), array(['bruteForce', 'dos', 'normal', 'pingScan', 'portScan'],
      dtype=object)]
[array(['ICMP ', 'TCP  ', 'UDP  '], dtype=object), array(['......', '....S.', '...R..', '...RS.', '.A....', '.A...F',
       '.A..S.', '.A..SF', '.A.R..', '.A.R.F', '.AP...', '.AP..F',
       '.AP.S.', '.AP.SF', '.APR..', '.APR.F', '.APRS.', '.APRSF'],
      dtype=object), array(['bruteForce', 'dos', 'normal', 'pingScan', 'portScan'],
      dtype=object)]
[array(['ICMP ', 'TCP  ', 'UDP  '], dtype=object), array(['......', '....S.', '...R..', '...RS.', '.A....', '.A...F',
       '.A..S.', '.A..SF', '.A.R..', '.A.R.F', '.A.RSF', '.AP...',
       '.AP..F', '.AP.S.', '.AP.SF', '.APR..', '.APR.F', '.APRS.',
       '.APRSF'], dtype=object), array(['bruteForce', 'dos', 'normal', 'pingScan', 'portScan'],
      dtype=object)]
[array(['ICMP ', 'TCP  ', 'UDP  '], dtype=object), array(['......', '....S.', '...R..', '...RS.', '.A....', '.A...F',
       '.A..S.', '.A..SF', '.A.R..', '.A.R.F', '.A.RSF', '.AP...',
       '.AP..F', '.AP.S.', '.AP.SF', '.APR..', '.APR.F', '.APRS.',
       '.APRSF'], dtype=object), array(['bruteForce', 'dos', 'normal', 'pingScan', 'portScan'],
      dtype=object)]
ML_algorithms_unknown...
Traceback (most recent call last):
  File "exec.py", line 13, in <module>
    exec(open("ML_algorithms_unknown.py").read())
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'classification_functions'
ML_algorithms_unknown.py:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from classification_functions import *
EFC 0 1
SVC 0 1
EFC 0 2
SVC 0 2
EFC 0 3
SVC 0 3
EFC 0 4
SVC 0 4
EFC 0 5
SVC 0 5
EFC 1 1
SVC 1 1
EFC 1 2
SVC 1 2
EFC 1 3
SVC 1 3
EFC 1 4
SVC 1 4
EFC 1 5
SVC 1 5
EFC 3 1
SVC 3 1
EFC 3 2
SVC 3 2
EFC 3 3
SVC 3 3
EFC 3 4
SVC 3 4
EFC 3 5
SVC 3 5
EFC 4 1
SVC 4 1
EFC 4 2
SVC 4 2
EFC 4 3
SVC 4 3
EFC 4 4
SVC 4 4
EFC 4 5
SVC 4 5
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
Exception in thread Thread-34:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
ML_algorithms_unknown.py:56: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  test_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_test".format(sets), squeeze=True, header=None).astype('int')
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 41, in SVC
    svc = SVC()
TypeError: SVC() missing 2 required positional arguments: 'removed' and 'sets'
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
ML_algorithms_unknown.py:58: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  train_labels = pd.read_csv("5-fold_sets/Discretized/Sets{}/y_train".format(sets), squeeze=True, header=None).astype('int')
Exception in thread Thread-33:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
Exception in thread Thread-39:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 71, in EFC
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 68, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 145, in classification_functions.MultiClassPredict
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    results = executor.map(PredictSubset, data_frac, n_jobs*[h_i_matrices], n_jobs*[coupling_matrices], n_jobs*[cutoffs_list], n_jobs*[Q], n_jobs*[train_labels])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    predicted = MultiClassPredict(np.array(test), h_i_matrices, coupling_matrices, cutoffs_list, Q, np.unique(train_labels))
  File "classification_functions_parallel.pyx", line 144, in classification_functions.MultiClassPredict
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 68, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 68, in _launch
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 68, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception in thread Thread-35:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception in thread Thread-37:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ML_algorithms_unknown.py", line 67, in EFC
    h_i_matrices, coupling_matrices, cutoffs_list = MultiClassFit(np.array(train), np.array(train_labels), Q, LAMBDA)
  File "classification_functions_parallel.pyx", line 88, in classification_functions.MultiClassFit
    with concurrent.futures.ProcessPoolExecutor() as executor:
  File "classification_functions_parallel.pyx", line 89, in classification_functions.MultiClassFit
    results = executor.map(FitClass, data_per_type, n_classes*[Q], n_classes*[LAMBDA])
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
